management:
  trace:
    enabled: true
    include: AUTHORIZATION_HEADER, COOKIE_HEADERS, PRINCIPAL, REMOTE_ADDRESS, REQUEST_HEADERS, RESPONSE_HEADERS, SESSION_ID, TIME_TAKEN
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.web.filter.CommonsRequestLogging: DEBUG
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: TRACE
    reactor.netty.http.client: TRACE
server:
  port : 8443
  forward-headers-strategy: framework
  servlet:
    context-path: /ms-tweet-service

spring:
  application:
    name: ms-tweet-service
  flyway:
    enabled: true
    baseline-on-migrate : true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
  #      This config will override the flyway because it will drop the user schema flyway
  #      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-coh7s5f79t8c73fuij7g-a.oregon-postgres.render.com/ms_tweet_service
    username: twitter_fnvb_user
    password: bWuOk2kJRpU0EtjUAPRoMhx3UU2ZF7uh
    driverClassName: org.postgresql.Driver

service:
  downstream-url:
    ms-tag-service: https://ms-tag-service.onrender.com
    ms-lists-service: https://ms-lists-service.onrender.com
    ms-user-service: https://ms-user-service-ndm5.onrender.com
    ms-notification-service: https://ms-notification-service.onrender.com
    ms-websocket-service: https://ms-websocket-service.onrender.com

google:
  api:
    url: https://www.googleapis.com/youtube/v3/videos?id=%s&key=%s&part=snippet,contentDetails,statistics,status
    key: AIzaSyAzjkMGVmYbeNnfkHFaViidfftvFot31lE

eureka:
  instance:
    hostname: ms-tweet-service-o6ph.onrender.com  # Public domain name
    nonSecurePort: 443  # Standard HTTP port
    securePortEnabled: true  # Enable if you're using HTTPS
    preferIpAddress: false  # Use the hostname instead of the IP address
    statusPageUrlPath: /actuator/info  # Default status page path
    healthCheckUrlPath: /actuator/health  # Default health check path
  client:
    serviceUrl:
      defaultZone: https://ms-eureka-server-2cvn.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true